sshawarma/sshawarma.github.io

_includes/footer.html, _sass/_footer.scss
Changed the footer to include some of my links.
=> Changed footer

_posts/2019-12-18-different-way-to-find-pythagorean-triples.md
Wrote a post on generating Pythagorean triples.
=> Wrote Pythagorean Triples Post

_posts/2019-12-19-how-to-read-a-computer-science-book.md
Posted a post I wrote on [dev.to](https://dev.to)
=> Wrote How To Read A Computer Science Book

_posts/2019-12-19-recursive-digit-reversal-formula.md
=> Added Digit Reversal post

_posts/2019-12-18-different-way-to-find-pythagorean-triples.md, _posts/2019-12-19-recursive-digit-reversal-formula.md
Made an edit to the post on recursive numbers by trying to space out the math equations. I'll do the same for the Pythagorean article.
=> Made edit to post

_posts/2019-12-25-5-git-commands-everyone-should-know.md
=> Added 5 Git Commands Everyone Should Know post

_posts/2019-01-04-five-projects-to-do-when-you-re-offline.md
5 Projects To Do Offline Post from dev.to
=> Added 5 Projects To Do Offline post from DEV

_posts/2020-01-15-cost-models-for-algorithmic-analysis.md
I added this post (from `dev.to`)
=> Added Cost Models for Algorithmic Analysis post

_posts/2020-05-02-fundamental-theorems-polynomials.md
Added post on fundamental theorem on polynomials.
=> Added post on Fundamental Theorems on Polynomials

_posts/2020-05-03-small-partial-fraction-problem.md
Added a post on partial fractions and their use in integration.
=> Added Small Partial Fractions post

_posts/2020-05-04-documenting-projects.md
Added Documenting Projects post.
=> Added Documenting Projects post

_posts/2020-05-09-removing-duplicates.md
Added Removing Duplicates article.
=> Added Removing Duplicates article

_posts/2020-05-11-disappeared-numbers.md
Added Disappeared Numbers article.
=> Added Disappeared Numbers solution Leetcode

_posts/2020-05-16-lispc-algorithm-1.md
Added C Algorithms and Data Structures post. This post talks about the repository `lispc-algorithms` and is a multi-part series of articles detailing this project.
=> Added post with title "C Algorithms and Data Structures Library: Part I"

_posts/2020-05-21-induction-and-direct-method-example.md
Added post showcasing induction and direct method of proof.
=> Added post "Induction and Direct Method Example"

_posts/2020-06-02-quick-note.md
Added a quick note on the book I'm reading.
=> Added quick note on the books I'm reading post

_posts/2020-06-14-c-algorithms-and-data-structures-library-part-2.md
=> Edited YAML

_posts/2020-06-16-number-of-1-bits-leetcode-exercise.md
Added post titled Number of 1 Bits Leetcode Exercise.
=> Added post titled Number of 1 Bits Leetcode Exercise

postgen.py
=> Converted title to lowercase

_layouts/default.html, _sass/base.scss, google3e178c50f123864d.html
=> Added Google Search

_includes/head.html, _includes/math.html, _includes/navigation.html, _layouts/default.html, _layouts/post.html, index.html, postgen.py
Did some refactoring (adding comments and changing order of includes).
=> Refactored Files

Gemfile, Gemfile.lock, _config.yml
=> Added Jekyll Sitemap

_includes/head.html, _layouts/post.html
=> Added <meta> tags

_sass/post.scss
Removed the font-weight attribute css.
=> Removed font-weight attribute css

_sass/about.scss, about.html
Changed the content of the about page.
=> Changed about page

README.md
=> Changed README.md heading

_config.yml, _includes/head.html, _layouts/default.html, _layouts/post.html, google3e178c50f123864d.html
=> Changed site configuration

_posts/2020-07-10-information-paralysis.md
Added article Information Paralysis.
=> Added article Information Paralysis

_posts/2020-07-10-information-paralysis.md
=> Fixed quote attribution
